"""PDF report generation service"""

import io
import unicodedata
from datetime import datetime
from fpdf import FPDF


def _latin(text: str) -> str:
    """Sanitize text for PDF core-fonts (latin-1). Replaces non-latin-1 chars with ASCII equivalents."""
    if not text:
        return ""
    text = unicodedata.normalize("NFKD", str(text))
    out = []
    for ch in text:
        if ord(ch) < 128:
            out.append(ch)
        elif unicodedata.category(ch).startswith("M"):
            # Decomposed combining mark — drop it (e.g. "é" -> "e" from NFKD)
            continue
        else:
            decomposed = unicodedata.normalize("NFKD", ch)
            ascii_part = "".join(c for c in decomposed if ord(c) < 128)
            out.append(ascii_part or "?")
    return "".join(out)


class SkinReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 160, 220)
        self.cell(0, 8, "AI Skin Specialist - Consultation Report", align="R")
        self.ln(12)
        self.set_draw_color(100, 160, 220)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def generate_consultation_pdf(
    consultation_id: str,
    patient_text: str,
    doctor_response: str,
    severity: str | None = None,
    created_at: str | None = None,
    image_url: str | None = None,
) -> bytes:
    pdf = SkinReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(30, 50, 90)
    pdf.cell(0, 14, "AI Skin Specialist", align="L")
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, "AI-Powered Dermatology Consultation Report", align="L")
    pdf.ln(12)

    # Info box
    pdf.set_fill_color(240, 247, 255)
    pdf.set_draw_color(100, 160, 220)
    pdf.rect(10, pdf.get_y(), 190, 30, "DF")
    y_before = pdf.get_y()
    pdf.set_xy(14, y_before + 3)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 5, f"Report ID: {consultation_id[:8]}...{consultation_id[-4:]}")
    pdf.set_xy(14, y_before + 10)
    pdf.cell(0, 5, f"Date: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
    pdf.set_xy(14, y_before + 17)
    pdf.cell(0, 5, f"Severity: {severity or 'Not specified'}")
    pdf.set_xy(14, y_before + 24)
    pdf.cell(0, 5, "Status: Completed" if not severity else f"Status: {severity}")
    pdf.set_y(y_before + 34)

    # Section: Your Concern
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 50, 90)
    pdf.set_fill_color(230, 240, 250)
    pdf.cell(0, 9, "  Your Skin Concern", fill=True)
    pdf.ln(12)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 5.5, patient_text)
    pdf.ln(6)

    # Section: AI Analysis
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 50, 90)
    pdf.set_fill_color(230, 240, 250)
    pdf.cell(0, 9, "  AI Analysis & Recommendations", fill=True)
    pdf.ln(12)

    clean_response = doctor_response.replace("*", "").replace("#", "")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 5.5, clean_response)
    pdf.ln(8)

    # Disclaimer
    pdf.set_y(-50)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 4, "Disclaimer: This report is generated by AI and is for informational purposes only. "
                        "It does not constitute a medical diagnosis or professional medical advice. "
                        "Always consult a qualified healthcare provider for medical concerns.")

    result = pdf.output(dest="S")
    if isinstance(result, bytearray):
        return bytes(result)
    if isinstance(result, str):
        return result.encode("latin-1")
    return bytes(result)


def generate_scanner_pdf(
    scan_id: str,
    detections: list[dict],
    explanation: str,
    treatment: str,
    recommendations: list[dict] | None = None,
    skin_score: float | None = None,
    image_url: str | None = None,
    created_at: str | None = None,
    severity: str | None = None,
    skin_profile: dict | None = None,
    products: list[dict] | None = None,
) -> bytes:
    pdf = SkinReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    recommendations = recommendations or []
    products = products or []
    skin_profile = skin_profile or {}

    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(30, 50, 90)
    pdf.cell(0, 14, "AI Skin Scanner Report", align="L")
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, "AI-Powered Skin Analysis & Personalized Recommendations", align="L")
    pdf.ln(12)

    pdf.set_fill_color(240, 247, 255)
    pdf.set_draw_color(100, 160, 220)
    pdf.rect(10, pdf.get_y(), 190, 35, "DF")
    y_before = pdf.get_y()
    pdf.set_xy(14, y_before + 3)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 5, f"Report ID: {scan_id[:8]}...{scan_id[-4:]}")
    pdf.set_xy(14, y_before + 10)
    pdf.cell(0, 5, f"Date: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
    pdf.set_xy(14, y_before + 17)
    pdf.cell(0, 5, f"Severity: {severity or 'Not specified'}")
    pdf.set_xy(14, y_before + 24)
    score_text = f"Skin Score: {skin_score}/10" if skin_score is not None else "Skin Score: N/A"
    pdf.cell(0, 5, score_text)
    pdf.set_xy(14, y_before + 30)
    status_text = "Status: Completed" if not severity else f"Status: {severity.title()}"
    pdf.cell(0, 5, status_text)
    pdf.set_y(y_before + 38)

    if detections:
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 50, 90)
        pdf.set_fill_color(230, 240, 250)
        pdf.cell(0, 9, "  Detected Skin Conditions", fill=True)
        pdf.ln(12)

        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(80, 80, 80)
        col_widths = [80, 25, 25, 60]
        pdf.set_fill_color(220, 235, 250)
        pdf.cell(col_widths[0], 7, "Condition", border=1, fill=True)
        pdf.cell(col_widths[1], 7, "Confidence", border=1, fill=True)
        pdf.cell(col_widths[2], 7, "Severity", border=1, fill=True)
        pdf.cell(col_widths[3], 7, "Details", border=1, fill=True)
        pdf.ln(7)

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(50, 50, 50)
        for d in detections[:8]:
            feature = _latin(str(d.get("feature", ""))[:30])
            confidence = f"{d.get('confidence', 0)}%"
            sev = _latin(str(d.get("severity", "mild")).title()[:10])
            desc = _latin(str(d.get("description", ""))[:55])
            pdf.cell(col_widths[0], 6, feature, border=1)
            pdf.cell(col_widths[1], 6, confidence, border=1)
            pdf.cell(col_widths[2], 6, sev, border=1)
            pdf.multi_cell(col_widths[3], 6, desc, border=1)

        pdf.ln(8)

    if skin_profile:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 50, 90)
        pdf.set_fill_color(230, 240, 250)
        pdf.cell(0, 9, "  Skin Profile", fill=True)
        pdf.ln(12)

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(50, 50, 50)
        profile_rows = [
            ("Skin Type", _latin(skin_profile.get("skin_type", "N/A"))),
            ("Fitzpatrick Type", _latin(skin_profile.get("fitzpatrick", "N/A"))),
            ("Undertone", _latin(skin_profile.get("undertone", "N/A"))),
            ("Tone", _latin(skin_profile.get("tone_label", "N/A"))),
        ]
        for label, value in profile_rows:
            if value and value != "N/A":
                pdf.cell(0, 5, f"  - {label}: {value}", align="L")
                pdf.ln(5)
        pdf.ln(6)

    if recommendations:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 50, 90)
        pdf.set_fill_color(230, 240, 250)
        pdf.cell(0, 9, "  Recommended Products & Medicines", fill=True)
        pdf.ln(12)

        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(80, 80, 80)
        rec_cols = [45, 70, 45]
        pdf.set_fill_color(220, 235, 250)
        pdf.cell(rec_cols[0], 7, "For", border=1, fill=True)
        pdf.cell(rec_cols[1], 7, "Recommended Product / Medicine", border=1, fill=True)
        pdf.cell(rec_cols[2], 7, "Use Frequency", border=1, fill=True)
        pdf.ln(7)

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(50, 50, 50)
        for rec in recommendations[:5]:
            feature = _latin(str(rec.get("feature", ""))[:22])
            product = _latin(str(rec.get("recommendation", ""))[:42])
            freq = _latin(str(rec.get("frequency", ""))[:22])
            pdf.cell(rec_cols[0], 6, feature, border=1)
            pdf.cell(rec_cols[1], 6, product, border=1)
            pdf.multi_cell(rec_cols[2], 6, freq, border=1)

        pdf.ln(8)

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 60)
        pdf.set_draw_color(200, 210, 220)
        pdf.multi_cell(0, 5, "Daily routine guide:")
        for rec in recommendations[:5]:
            routine = str(rec.get("routine", ""))[:160]
            if routine:
                pdf.cell(0, 5, f"  - {rec.get('feature', '')}: {routine}", align="L")
                pdf.ln(5)
        pdf.ln(6)

    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 50, 90)
    pdf.set_fill_color(230, 240, 250)
    pdf.cell(0, 9, "  Analysis Summary", fill=True)
    pdf.ln(12)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 5.5, _latin(explanation))
    pdf.ln(8)

    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 50, 90)
    pdf.set_fill_color(230, 240, 250)
    pdf.cell(0, 9, "  Treatment & Recommendations", fill=True)
    pdf.ln(12)
    clean_treatment = _latin(treatment).replace("*", "").replace("#", "")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 5.5, clean_treatment)
    pdf.ln(8)

    if products:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 50, 90)
        pdf.set_fill_color(230, 240, 250)
        pdf.cell(0, 9, "  Recommended Products & Medicines", fill=True)
        pdf.ln(12)

        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(80, 80, 80)
        prod_cols = [62, 20, 80, 28]
        pdf.set_fill_color(220, 235, 250)
        pdf.cell(prod_cols[0], 7, "Product / Brand", border=1, fill=True)
        pdf.cell(prod_cols[1], 7, "Price", border=1, fill=True)
        pdf.cell(prod_cols[2], 7, "Key Ingredients", border=1, fill=True)
        pdf.cell(prod_cols[3], 7, "Buy Link", border=1, fill=True)
        pdf.ln(7)

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(50, 50, 50)
        for p in products[:4]:
            name = _latin(str(p.get("brand", "") + " " + p.get("name", "")).strip()[:58])
            price = _latin(str(p.get("price_range", ""))[:18])
            ingredients = _latin(", ".join(p.get("key_ingredients", []) or [])[:74])
            url = _latin(str(p.get("amazon_search_url", "") or ""))
            pdf.cell(prod_cols[0], 6, name, border=1)
            pdf.cell(prod_cols[1], 6, price, border=1)
            pdf.multi_cell(prod_cols[2], 6, ingredients, border=1)
            pdf.set_font("Helvetica", "U", 8)
            pdf.set_text_color(30, 100, 200)
            pdf.cell(prod_cols[3], 6, "amazon.com" if url else "N/A", border=1, link=url)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(50, 50, 50)
            pdf.ln(6)
        pdf.ln(6)

        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(0, 4, "Buy links open a search for the product on Amazon. Prices and availability vary by region.")
        pdf.ln(6)

    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 50, 90)
    pdf.set_fill_color(230, 240, 250)
    pdf.cell(0, 9, "  Doctor's Assessment & Follow-up", fill=True)
    pdf.ln(12)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 5.5, _latin(explanation))
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(180, 40, 40)
    pdf.multi_cell(0, 5, "When to see a dermatologist (Red Flags): "
                         "if symptoms worsen, spread, become painful, bleed, or do not improve after 2-4 weeks of consistent care. "
                         "If you notice a new or changing mole, a sore that will not heal, or rapid changes in skin appearance, "
                         "seek professional evaluation promptly.")
    pdf.ln(6)

    if skin_score is not None:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 50, 90)
        pdf.set_fill_color(230, 240, 250)
        pdf.cell(0, 9, "  Skin Health Score", fill=True)
        pdf.ln(12)
        pdf.set_font("Helvetica", "", 12)
        score_color = (60, 170, 90) if skin_score >= 7 else (245, 150, 60) if skin_score >= 4 else (220, 50, 50)
        pdf.set_text_color(*score_color)
        pdf.cell(0, 8, f"  {skin_score:.1f} / 10", align="L")
        pdf.ln(10)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(100, 100, 100)
        if skin_score >= 7:
            pdf.cell(0, 5, "Your skin is in good condition! Maintain your routine.", align="L")
        elif skin_score >= 4:
            pdf.cell(0, 5, "Your skin shows some concerns. Address soon with proper care.", align="L")
        else:
            pdf.cell(0, 5, "Your skin needs attention. Consider consulting a dermatologist.", align="L")
        pdf.ln(10)

    pdf.set_y(-60)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 4, "Disclaimer: This report is generated by AI and is for informational purposes only. "
                        "It does not constitute a medical diagnosis or professional medical advice. "
                        "Always consult a qualified healthcare provider for medical concerns.")

    result = pdf.output(dest="S")
    if isinstance(result, bytearray):
        return bytes(result)
    if isinstance(result, str):
        return result.encode("latin-1")
    return bytes(result)
