"""PDF report generation service"""

import io
from datetime import datetime
from fpdf import FPDF


class SkinReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 160, 220)
        self.cell(0, 8, "AI Skin Specialist - Consultation Report", align="R")
        self.ln(12)
        self.set_draw_color(100, 160, 220)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def generate_consultation_pdf(
    consultation_id: str,
    patient_text: str,
    doctor_response: str,
    severity: str | None = None,
    created_at: str | None = None,
    image_url: str | None = None,
) -> bytes:
    pdf = SkinReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(30, 50, 90)
    pdf.cell(0, 14, "AI Skin Specialist", align="L")
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, "AI-Powered Dermatology Consultation Report", align="L")
    pdf.ln(12)

    # Info box
    pdf.set_fill_color(240, 247, 255)
    pdf.set_draw_color(100, 160, 220)
    pdf.rect(10, pdf.get_y(), 190, 30, "DF")
    y_before = pdf.get_y()
    pdf.set_xy(14, y_before + 3)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 5, f"Report ID: {consultation_id[:8]}...{consultation_id[-4:]}")
    pdf.set_xy(14, y_before + 10)
    pdf.cell(0, 5, f"Date: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
    pdf.set_xy(14, y_before + 17)
    pdf.cell(0, 5, f"Severity: {severity or 'Not specified'}")
    pdf.set_xy(14, y_before + 24)
    pdf.cell(0, 5, "Status: Completed" if not severity else f"Status: {severity}")
    pdf.set_y(y_before + 34)

    # Section: Your Concern
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 50, 90)
    pdf.set_fill_color(230, 240, 250)
    pdf.cell(0, 9, "  Your Skin Concern", fill=True)
    pdf.ln(12)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 5.5, patient_text)
    pdf.ln(6)

    # Section: AI Analysis
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 50, 90)
    pdf.set_fill_color(230, 240, 250)
    pdf.cell(0, 9, "  AI Analysis & Recommendations", fill=True)
    pdf.ln(12)

    clean_response = doctor_response.replace("*", "").replace("#", "")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 5.5, clean_response)
    pdf.ln(8)

    # Disclaimer
    pdf.set_y(-50)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 4, "Disclaimer: This report is generated by AI and is for informational purposes only. "
                        "It does not constitute a medical diagnosis or professional medical advice. "
                        "Always consult a qualified healthcare provider for medical concerns.")

    result = pdf.output(dest="S")
    if isinstance(result, bytearray):
        return bytes(result)
    if isinstance(result, str):
        return result.encode("latin-1")
    return bytes(result)
